### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by SillyInventor**
Missing semicolons, no docs,  bad indentation, mixed cammal case and underscored, bad spacing etc.

### CODE REVIEW

**Comment by SillyInventor** [comment]
Fixed the conflict from Ryan's merge.

**Comment by srtate** [comment]
Unfortunately, the change from 4-space indentation to 2-space makes the diff almost impossible to review, since basically every line changed. I'd like to separate that issue from the other changes. I'm not a fan of 2-space indentation, but looking at various style guides this style seems to have "won" in most of them, so I can just hold my nose and go with it. I would like to be able to review the changes in this pull request, however. You could either separate these two issues into two pull requests (reindent + other changes), or I could reindent the main branch with two space indentation and you could update this pull request from there.

Preferences?

**Comment by SillyInventor** [comment]
If you're up for making the indentation change for the main branch, that'd be nice of you. However, I'm ok with either.

**Comment by SillyInventor** [comment]
Too many conflicts to fix.

**Pull request closed without merging**
